"""Catalog of campus kit pieces for the Blender authoring add-on."""

from __future__ import annotations

PIECES: tuple[dict, ...] = (
    {
        "id": "mass_block",
        "label": "Mass Block",
        "group": "ALS_MassBlock",
        "category": "Massing",
        "stem": "MassBlock",
        "bevel": 0.22,
        "defaults": {"Size": (2.4, 2.4, 3.2), "Inset": 0.0},
        "material_sockets": {"Material": "primary"},
    },
    {
        "id": "curtain_wall",
        "label": "Curtain Wall",
        "group": "ALS_CurtainWall",
        "category": "Facade",
        "stem": "CurtainWall",
        "bevel": 0.0,
        "defaults": {
            "Width": 4.0,
            "Height": 4.8,
            "Depth": 0.22,
            "Columns": 3,
            "Rows": 2,
            "Frame": 0.08,
            "Brace": True,
        },
        "material_sockets": {"GlassMaterial": "primary", "FrameMaterial": "secondary"},
    },
    {
        "id": "ribbon_window",
        "label": "Ribbon Window",
        "group": "ALS_RibbonWindow",
        "category": "Facade",
        "stem": "RibbonWindow",
        "bevel": 0.0,
        "defaults": {"Length": 6.0, "Height": 1.1, "Depth": 0.16, "Mullions": 7, "MullionWidth": 0.08},
        "material_sockets": {"GlassMaterial": "primary", "FrameMaterial": "secondary"},
    },
    {
        "id": "window_rhythm",
        "label": "Window Rhythm",
        "group": "ALS_WindowRhythm",
        "category": "Facade",
        "stem": "Windows",
        "bevel": 0.0,
        "defaults": {"Count": 6, "Spacing": 0.9, "Width": 0.56, "Depth": 0.18, "Height": 1.65},
        "material_sockets": {"Material": "primary"},
    },
    {
        "id": "hvac_bank",
        "label": "HVAC Bank",
        "group": "ALS_HvacBank",
        "category": "Roof",
        "stem": "HvacBank",
        "bevel": 0.04,
        "defaults": {"Size": (2.4, 1.4, 0.85), "FanCount": 3, "FanRadius": 0.28},
        "material_sockets": {"HousingMaterial": "secondary", "FanMaterial": "secondary"},
    },
    {
        "id": "cooling_stack",
        "label": "Cooling Stack",
        "group": "ALS_CoolingStack",
        "category": "Roof",
        "stem": "CoolingStack",
        "bevel": 0.0,
        "defaults": {"Radius": 0.5, "Height": 1.4, "CapScale": 1.2, "CapHeight": 0.2},
        "material_sockets": {"Material": "secondary"},
    },
    {
        "id": "pipe_run",
        "label": "Pipe Run",
        "group": "ALS_PipeRun",
        "category": "Roof",
        "stem": "PipeRun",
        "bevel": 0.0,
        "defaults": {"Length": 3.2, "Radius": 0.09, "Count": 3, "Spacing": 0.22},
        "material_sockets": {"Material": "secondary"},
    },
    {
        "id": "skylight",
        "label": "Skylight",
        "group": "ALS_Skylight",
        "category": "Roof",
        "stem": "Skylight",
        "bevel": 0.02,
        "defaults": {"Width": 1.4, "Depth": 1.4, "Height": 0.18, "Frame": 0.08},
        "material_sockets": {"GlassMaterial": "primary", "FrameMaterial": "emissive"},
    },
    {
        "id": "entrance",
        "label": "Entrance",
        "group": "ALS_Entrance",
        "category": "Entry",
        "stem": "Entrance",
        "bevel": 0.04,
        "defaults": {
            "Width": 2.4,
            "StepCount": 3,
            "StepDepth": 0.32,
            "StepHeight": 0.16,
            "AwningDepth": 1.1,
            "AwningThickness": 0.12,
        },
        "material_sockets": {"StairMaterial": "concrete", "AwningMaterial": "secondary"},
    },
    {
        "id": "accent_column",
        "label": "Accent Column",
        "group": "ALS_AccentColumn",
        "category": "Entry",
        "stem": "AccentColumn",
        "bevel": 0.0,
        "defaults": {"Radius": 0.22, "Height": 4.8},
        "material_sockets": {"Material": "accent"},
    },
    {
        "id": "site_pad",
        "label": "Site Pad",
        "group": "ALS_SitePad",
        "category": "Site",
        "stem": "SitePad",
        "bevel": 0.06,
        "defaults": {"Size": (12.0, 10.0, 0.45), "DivisionsX": 6, "DivisionsY": 5, "Groove": 0.03},
        "material_sockets": {"Material": "concrete"},
    },
    {
        "id": "bollard_run",
        "label": "Bollard Run",
        "group": "ALS_BollardRun",
        "category": "Site",
        "stem": "Bollards",
        "bevel": 0.0,
        "defaults": {"Count": 4, "Spacing": 1.4, "Height": 0.55, "Radius": 0.08},
        "material_sockets": {"Material": "accent"},
    },
    {
        "id": "hedge_run",
        "label": "Hedge Run",
        "group": "ALS_HedgeRun",
        "category": "Site",
        "stem": "Hedge",
        "bevel": 0.08,
        "defaults": {"Length": 6.0, "Width": 0.45, "Height": 0.55},
        "material_sockets": {"Material": "vegetation"},
    },
    {
        "id": "planter",
        "label": "Planter",
        "group": "ALS_Planter",
        "category": "Site",
        "stem": "Planter",
        "bevel": 0.06,
        "defaults": {"Size": 1.1, "Height": 0.45, "Wall": 0.08},
        "material_sockets": {"BoxMaterial": "concrete", "SoilMaterial": "vegetation"},
    },
    {
        "id": "plaza_mark",
        "label": "Plaza Mark",
        "group": "ALS_PlazaMark",
        "category": "Site",
        "stem": "PlazaMark",
        "bevel": 0.0,
        "defaults": {"Width": 3.6, "Depth": 2.4, "LineWidth": 0.08, "Height": 0.04},
        "material_sockets": {"Material": "emissive"},
    },
    {
        "id": "status_pylon",
        "label": "Status Pylon",
        "group": "ALS_StatusPylon",
        "category": "State",
        "stem": "StatusPylon",
        "bevel": 0.06,
        "defaults": {"Width": 0.28, "Height": 1.9},
        "material_sockets": {"Material": "emissive"},
    },
    {
        "id": "fence_run",
        "label": "Fence Run",
        "group": "ALS_FenceRun",
        "category": "State",
        "stem": "Fence",
        "bevel": 0.0,
        "defaults": {"Length": 12.0, "Spacing": 2.0, "Height": 1.65, "PostSize": 0.16},
        "material_sockets": {"Material": "secondary"},
    },
    {
        "id": "scan_arch",
        "label": "Scan Arch",
        "group": "ALS_ScanArch",
        "category": "State",
        "stem": "ScanArch",
        "bevel": 0.0,
        "defaults": {"Width": 2.0, "Height": 2.6, "PostSize": 0.22},
        "material_sockets": {"Material": "emissive"},
    },
)

SCATTER_PIECES: tuple[dict, ...] = (
    {
        "id": "tree",
        "label": "Tree (scatter only)",
        "group": "ALS_Tree",
        "category": "Scatter",
        "stem": "Tree",
        "bevel": 0.0,
        "defaults": {"TrunkRadius": 0.12, "TrunkHeight": 1.1, "CrownRadius": 0.7, "CrownHeight": 1.45},
        "material_sockets": {"TrunkMaterial": "secondary", "CrownMaterial": "vegetation"},
    },
)

LAYER_COLLECTIONS = {
    "Base": {
        "LabStage1": "Export__LabStage1",
        "Compute": "Export__Compute",
        "Research": "Export__Research",
    },
    "Growth": "Export__Growth",
    "Overload": "Export__Overload",
    "Scrutiny": "Export__Scrutiny",
}

MATERIAL_ROLES = {
    "primary": "Architecture_Cream",
    "secondary": "Metal_Dark",
    "accent": "Architecture_Coral",
    "concrete": "Concrete_Shadow",
    "vegetation": "Vegetation",
    "emissive": "Status_Growth",
}

BUILDING_LABELS = {
    "Export__LabStage1": (
        "Lab Stage 1",
        "Starting lab mass on the research plot.\nExports lab_stage1.glb",
    ),
    "Export__Compute": (
        "Compute",
        "Persistent compute building.\nState dressing from growth, overload, and scrutiny attaches here.\nExports compute.glb",
    ),
    "Export__Research": (
        "Research",
        "Persistent research terraces.\nState dressing from growth, overload, and scrutiny attaches here.\nExports research.glb",
    ),
}

